global using MediaMarktProjectApi.Domain.Entities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using MediaMarktProjectApi.Domain.Interfaces;
global using MediaMarktProjectApi.Infrastructure.Persistance;
global using MediaMarktProjectApi.Infrastructure.Repositories;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using MediaMarktProjectApi.Domain.Common;