// <auto-generated />
using System;
using MediaMarktProjectApi.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaMarktProjectApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260113130052_addDefaultData")]
    partial class addDefaultData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaMarktProjectApi.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Televisión"
                        },
                        new
                        {
                            Id = new Guid("a11111e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Name = "Hogar"
                        },
                        new
                        {
                            Id = new Guid("6050e3c9-5b15-406f-a9a5-077e64da2cff"),
                            Name = "Consolas"
                        },
                        new
                        {
                            Id = new Guid("bee061d2-d289-4ab3-b012-4aa4e30457cb"),
                            Name = "Telefonía"
                        });
                });

            modelBuilder.Entity("MediaMarktProjectApi.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b741490a-5240-4428-a55e-1b970c07992f"),
                            CategoryId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "65 pulgadas OLED",
                            Name = "Televisor 4K LG LED",
                            Price = 699.99m
                        },
                        new
                        {
                            Id = new Guid("2fab0ea9-2321-439d-bef1-10b6e24720ff"),
                            CategoryId = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "60 pulgadas OLED",
                            Name = "Televisor 4K Samsung QLED",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = new Guid("2094c4a2-4f10-454c-a1ef-711b92b807c2"),
                            CategoryId = new Guid("a11111e9-2ba9-473a-a40f-e38cb54f9b35"),
                            Description = "Bombilla LED de larga duración con más de 20.000 horas.",
                            Name = "Bombilla luz LED 20W White",
                            Price = 21.99m
                        },
                        new
                        {
                            Id = new Guid("48297667-adcf-49f6-9dc9-ee6331744c1f"),
                            CategoryId = new Guid("6050e3c9-5b15-406f-a9a5-077e64da2cff"),
                            Description = "Playstation 5 con 1 mando incluido, color blanco",
                            Name = "PS5 Slim",
                            Price = 499m
                        },
                        new
                        {
                            Id = new Guid("0eae58f4-0066-4d45-8537-bb71a9afcd62"),
                            CategoryId = new Guid("6050e3c9-5b15-406f-a9a5-077e64da2cff"),
                            Description = "Switch 2 256GB en color negro, azul y rojo Neón",
                            Name = "Switch 2 256GB + MarioBROS",
                            Price = 509m
                        },
                        new
                        {
                            Id = new Guid("2feb7bd9-c759-479a-aa7c-55787034cc68"),
                            CategoryId = new Guid("bee061d2-d289-4ab3-b012-4aa4e30457cb"),
                            Description = "El Samsung Galaxy A56 5G es un dispositivo potente y equilibrado que ofrece un excelente rendimiento, conectividad avanzada y una experiencia visual envolvente. Con un procesador Exynos 1580",
                            Name = "Samsung Galaxy A56 5G, 8GB RAM",
                            Price = 509m
                        });
                });

            modelBuilder.Entity("MediaMarktProjectApi.Domain.Entities.Product", b =>
                {
                    b.HasOne("MediaMarktProjectApi.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MediaMarktProjectApi.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
